version: '3'

services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codebase
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mariadb:
    image: 'mariadb:latest'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: codebase
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password

    volumes:
      - ./db-data/mariadb:/docker-entrypoint-initdb.d
